version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    dotnet build src --configuration Release
    dotnet test src --configuration Release --no-build --verbosity diag
artifacts:
- path: nugets\**\*.nupkg